# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MetricsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QListWidget
import pandas as pd
import pickle

class ListWidget(QListWidget):
    def clicked(self, item):
        QMessageBox.information(self, "ListWidget", "ListWidget: " + item.text())


class TaskWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 500)
        MainWindow.setToolTipDuration(5)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(650, 440, 113, 32))
        self.pushButtonNext.setToolTipDuration(10)
        self.pushButtonNext.setObjectName("pushButtonNext")

        self.pushButtonBuild = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBuild.setGeometry(QtCore.QRect(350, 440, 130, 32))
        self.pushButtonBuild.setToolTipDuration(10)
        self.pushButtonBuild.setObjectName("pushButtonBuild")

        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(50, 440, 113, 32))
        self.pushButtonBack.setToolTipDuration(10)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 30, 381, 31))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 70, 400, 300))
        self.horizontalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("verticalLayout")

        self.list1 = QListWidget()

        self.list1.clicked.connect(self.listview_clicked)
        # self.list.setGeometry(QtCore.QRect(100, 100, 100, 100))
        self.horizontalLayout.addWidget(self.list1)

        self.list2 = QListWidget()

        self.list2.clicked.connect(self.listview_clicked)
        # self.list.setGeometry(QtCore.QRect(100, 100, 100, 100))
        self.horizontalLayout.addWidget(self.list2)

        self.list3 = QListWidget()
        # self.fillList()
        self.list3.clicked.connect(self.listview_clicked)
        # self.list.setGeometry(QtCore.QRect(100, 100, 100, 100))
        self.horizontalLayout.addWidget(self.list3)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonNext.setText(_translate("MainWindow", "Вперед"))
        self.pushButtonBack.setText(_translate("MainWindow", "Назад"))
        self.pushButtonBuild.setText(_translate("MainWindow", "Построить график"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:13pt;\">Сравнение численных графиков</span></p></body></html>"))

    def fillList(self):
        with open('settings.py', 'rb') as f:
            data = pickle.load(f)
            ref = data['MODULE_SETTINGS']['data']['path']

        data = pd.read_excel(ref)
        i = 0
        for column in data.columns:
            i += 1
            self.list1.insertItem(i, column)
        i = 0
        for column in data.columns:
            i += 1
            self.list2.insertItem(i, column)
        i = 0
        for column in data.columns:
            i += 1
            self.list3.insertItem(i, column)
