# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TreeVisualWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ContinuousMethods(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 521, 81))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 140, 600, 200))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.checkBoxKolmSmirn= QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxKolmSmirn.setObjectName("checkBoxKolmSmirn")
        self.verticalLayout.addWidget(self.checkBoxKolmSmirn)

        self.checkBoxStudentDepend = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxStudentDepend.setObjectName("checkBoxStudentDepend")
        self.verticalLayout.addWidget(self.checkBoxStudentDepend)

        self.checkBoxStudentIndepend = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxStudentIndepend.setObjectName("checkBoxStudentIndepend")
        self.verticalLayout.addWidget(self.checkBoxStudentIndepend)

        self.checkBoxMannWhitney = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxMannWhitney.setObjectName("checkBoxMannWhitney")
        self.verticalLayout.addWidget(self.checkBoxMannWhitney)

        self.checkBoxWilcoxon = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxWilcoxon.setObjectName("checkBoxWilcoxon")
        self.verticalLayout.addWidget(self.checkBoxWilcoxon)

        self.pushButtonDone = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDone.setGeometry(QtCore.QRect(460, 420, 113, 32))
        self.pushButtonDone.setObjectName("pushButtonDone")

        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(330, 420, 113, 32))
        self.pushButtonBack.setObjectName("pushButtonBack")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Выберите метод сравнения </span></p><p><span style=\" font-size:18pt;\"></span></p></body></html>"))
        self.checkBoxKolmSmirn.setText(_translate("MainWindow", "  Тест Колмогорова Смирнова"))
        self.checkBoxStudentIndepend.setText(_translate("MainWindow", "  T-критерий Стьюдента для независимых переменных"))
        self.checkBoxStudentDepend.setText(_translate("MainWindow", "  T-критерий Стьюдента для зависимых переменных"))
        self.checkBoxMannWhitney.setText(_translate("MainWindow", " U-критерий Манна-Уитни"))
        self.checkBoxWilcoxon.setText(_translate("MainWindow", "  T-критерий Уилкоксона"))
        self.pushButtonDone.setText(_translate("MainWindow", "Завершить"))
        self.pushButtonBack.setText(_translate("MainWindow", "Назад"))
